-- MySQL Script generated by MySQL Workbench
-- Tue Nov 30 08:37:45 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema padaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema padaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `padaria` DEFAULT CHARACTER SET utf8 ;
USE `padaria` ;

-- -----------------------------------------------------
-- Table `padaria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padaria`.`cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT ,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(12) NOT NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `padaria`.`chef`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `padaria`.`chef` (
  `idChef` INT NOT NULL  AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(12) NOT NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `especialidade` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idChef`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
